---
kind: pipeline
type: kubernetes
name: build
steps:
  - name: docker-build-publish
    image: plugins/docker
    settings:
      repo: registry.andredasilva.dev/hub.andasilva.ch
      tags: main
      registry: https://registry.andredasilva.dev
      username:
        from_secret: registry-username
      password:
        from_secret: registry-password
trigger:
  branch:
    - main

---
kind: pipeline
type: kubernetes
name: update-pod
steps:
  - name: restart-pod
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh-host
      username:
        from_secret: ssh-username
      port:
        from_secret: ssh-port
      key:
        from_secret: ssh-key
      script:
        - kubectl delete --all pods --namespace=registry
depends_on:
  - build
trigger:
  branch:
    - main